apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application1-env2
  namespace: argocd
  labels:
    env: env2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: https://kubernetes.default.svc
    namespace: application1-env2
  project: some-team
  source:
    helm:
      releaseName: application1
      valueFiles:
        - values.yaml
        - values.deploy-env2.yaml
    path: charts/application1
    repoURL: https://github.com/maciob/gitops-demo
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true