apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-env-1
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/maciob/gitops-demo
    targetRevision: main
    path: apps/environment1
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true